export const AMBIENT_GUIDE = [
  '## ambient — 作曲规范',
  '**BPM**: 60–90 | **Bank**: RolandTR808 | **Scale**: major / lydian',
  '**推荐层序**: pad → lead → fx（无鼓，或仅每 4 小节一个 soft kick）',
  '',
  '### pad',
  'long evolving pad，attack > 1s，release > 2s，low gain ~0.3。必须加 `.lpf(sine.range(200,800).slow(8)).lpq(3)`。',
  '```',
  'note("c3 e3 g3")',
  '  .s("juno")',
  '  .gain(0.3)',
  '  .attack(1.5)',
  '  .release(3)',
  '  .room(4)',
  '  .delay(0.5)',
  '  .lpf(sine.range(200,800).slow(8))',
  '  .lpq(3)',
  '```',
  '',
  '### lead',
  'sparse single notes，lots of ~ rests，.room(0.7)，scale in major or lydian。',
  '```',
  'note("c4 ~ ~ e4 ~ ~ g4 ~")',
  '  .s("sine")',
  '  .gain(0.4)',
  '  .room(0.7)',
  '  .attack(0.5)',
  '  .release(1.5)',
  '```',
  '',
  '### fx',
  'occasional perlin-modulated noise，sparse metallic textures。',
  '```',
  's("metal(3,16)")',
  '  .gain(0.2)',
  '  .room(2)',
  '  .gain(perlin.range(.1,.3).slow(16))',
  '```',
  '',
  '### drums',
  '无鼓，或仅每 4 小节一个超轻 kick。',
  '```',
  's("bd/4")',
  '  .bank("RolandTR808")',
  '  .gain(0.3)',
  '```',
  '',
  '**风格标志技巧**: `.room(0.8)` 或更高 + `.attack(≥1).release(≥2)` on pads；pad 滤波器必须用 `sine.range` 调制，制造有机演变感。',
].join('\n');
