export const DNB_GUIDE = [
  '## dnb — 作曲规范',
  '**BPM**: 165–180 | **Bank**: RolandTR909 | **Scale**: minor',
  '**推荐层序**: drums → bass → pad',
  '',
  '### drums',
  'amen-style break，snare on 2 and 4 with ghost notes。`.struct("x ~ [x x] ~")` on snare。',
  '```',
  's("bd ~ ~ ~ bd ~ ~ ~")',
  '  .bank("RolandTR909")',
  '  .gain(0.85)',
  '',
  's("sn")',
  '  .bank("RolandTR909")',
  '  .struct("x ~ [x x] ~")',
  '  .gain(0.75)',
  '',
  's("hh(5,8)")',
  '  .bank("RolandTR909")',
  '  .gain(0.4)',
  '```',
  '',
  '### bass',
  'reese bass 或 sub-rolling bass，root note c2–f2，sparse with rests；growling filter movement。',
  '```',
  'note("c2 ~ [c2 eb2] ~")',
  '  .s("sawtooth")',
  '  .lpf(sine.range(100,400).slow(8))',
  '  .gain(0.8)',
  '  .decay(0.3)',
  '```',
  '',
  '### pad',
  'atmospheric long pad in minor，very low gain ~0.3，high reverb。',
  '```',
  'note("c3 eb3 g3")',
  '  .s("juno")',
  '  .gain(0.3)',
  '  .room(3)',
  '  .attack(1)',
  '  .release(2)',
  '```',
  '',
  '**风格标志技巧**: break pattern 用 `.struct("x ~ [x x] ~")` on snare 制造 amen break 感；bass lpf sweep `.lpf(sine.range(100,400).slow(8))` 制造 growling 效果。',
].join('\n');
