export const HOUSE_GUIDE = [
  '## house — 作曲规范',
  '**BPM**: 118–128 | **Bank**: RolandTR909 | **Scale**: minor / dorian',
  '**推荐层序**: drums → hh → bass → pad',
  '',
  '### drums',
  'four-on-the-floor kick，clap on 2 and 4。',
  '```',
  's("bd*4")',
  '  .bank("RolandTR909")',
  '  .gain(0.85)',
  '',
  's("~ cp ~ cp")',
  '  .bank("RolandTR909")',
  '  .gain(0.75)',
  '```',
  '',
  '### hh',
  'open hi-hat on off-beats，pumping feel，gain 0.4–0.5。',
  '```',
  's("~ oh ~ oh")',
  '  .bank("RolandTR909")',
  '  .gain(sine.range(.3,.6).slow(2))',
  '',
  's("hh(5,8)")',
  '  .bank("RolandTR909")',
  '  .gain(0.45)',
  '```',
  '',
  '### bass',
  'pumping sub bass，root notes on every kick；sidechain gain pattern。c2–g2，.lpf(400)。',
  '```',
  'note("c2 c2 eb2 f2")',
  '  .s("sawtooth")',
  '  .lpf(400)',
  '  .gain("<.2 1@3>*2")',
  '```',
  '',
  '### pad',
  'sustained chord stabs，low gain ~0.4，.room(1.5)。',
  '```',
  'note("c3 eb3 g3 bb3")',
  '  .s("juno")',
  '  .gain(0.4)',
  '  .room(1.5)',
  '  .attack(0.1)',
  '```',
  '',
  '**风格标志技巧**: 精确用 `s("bd*4")` four-on-floor + euclidean hi-hat (5,8)；bass `.gain("<.2 1@3>*2")` 模拟 sidechain 压缩感。',
].join('\n');
