export const JAZZ_GUIDE = [
  '## jazz — 作曲规范',
  '**BPM**: 90–110 | **Bank**: RolandTR909 | **Scale**: dorian / lydian',
  '**推荐层序**: drums → bass → pad（→ lead）',
  '',
  '### drums',
  'swing ride pattern with brush feel；euclidean hi-hat，soft gain 0.5–0.65，sparse kick。`.gain(perlin.range(.45,.65))` for human-feel dynamics。',
  '```',
  's("hh(5,8)")',
  '  .bank("RolandTR909")',
  '  .gain(perlin.range(.45,.65))',
  '',
  's("bd ~ ~ ~")',
  '  .bank("RolandTR909")',
  '  .gain(0.55)',
  '',
  's("~ ~ sd ~")',
  '  .bank("RolandTR909")',
  '  .gain(perlin.range(.5,.65))',
  '```',
  '',
  '### bass',
  'walking bass in dorian or lydian，quarter-note feel；c2–g3，stepwise motion，.lpf(500)。',
  '```',
  'note("c2 d2 eb2 f2 g2 f2 eb2 d2")',
  '  .s("sawtooth")',
  '  .lpf(500)',
  '  .gain(0.65)',
  '```',
  '',
  '### pad',
  'warm chord voicings with delay；gain ~0.4，.delay(0.3).room(1.5)，short sustain。',
  '```',
  'chord("<Am7 Dm7>/4")',
  '  .dict("ireal")',
  '  .voicing()',
  '  .gain(0.4)',
  '  .delay(0.3)',
  '  .room(1.5)',
  '  .attack(0.05)',
  '  .release(0.8)',
  '```',
  '',
  '### lead',
  'melodic improvisation with lots of ~ rests，dorian scale，.room(1)。',
  '```',
  'n("0 ~ 2 ~ 4 ~ 2 ~")',
  '  .scale("C4:dorian")',
  '  .s("sine")',
  '  .gain(0.45)',
  '  .room(1)',
  '  .attack(0.05)',
  '  .release(0.5)',
  '```',
  '',
  '**风格标志技巧**: `chord("<Am7 Dm7>/4").dict("ireal").voicing()` for real chord changes；drums `perlin.range(.45,.65)` 制造 human-feel 动态；走低音用 stepwise motion。',
].join('\n');
