export const LOFI_GUIDE = [
  '## lofi — 作曲规范',
  '**BPM**: 70–90 | **Bank**: RolandTR808 | **Scale**: minor / dorian',
  '**推荐层序**: drums → hh → bass → pad',
  '',
  '### drums',
  'lazy boom-bap groove，sparse ghost snare，swing feel。',
  '```',
  's("bd ~ bd ~")',
  '  .bank("RolandTR808")',
  '  .gain(0.8)',
  '  .late("[0 .01 0 .02]*4")',
  '```',
  '',
  '### hh',
  'soft closed hi-hat，多在 off-beat，euclidean 节奏。gain ≤ 0.45。',
  '```',
  's("hh(5,8)")',
  '  .bank("RolandTR808")',
  '  .gain(0.4)',
  '```',
  '',
  '### bass',
  'walking bass in minor，稀疏，多休止；note range c2–g2。',
  '```',
  'note("c2 ~ eb2 ~")',
  '  .s("sawtooth")',
  '  .lpf(400)',
  '  .gain(0.7)',
  '  .gain(perlin.range(.5,.8))',
  '```',
  '',
  '### pad',
  'warm electric-piano feel，slow attack，低 gain ~0.35，配合 room。',
  '```',
  'note("c3 eb3 g3")',
  '  .s("juno")',
  '  .gain(0.35)',
  '  .room(2)',
  '  .lpf(sine.range(800,2000).slow(16))',
  '```',
  '',
  '**风格标志技巧**: hi-hat 用 `.late("[0 .01 0 .02]*4")` 或 `.swing(4)` 制造 lazy drunk groove；鼓点 boom-bap feel，kick 不在每拍都打。bass `.gain(perlin.range(.5,.8))` 制造有机呼吸感动态。',
].join('\n');
