export const SYNTHWAVE_GUIDE = [
  '## synthwave — 作曲规范',
  '**BPM**: 90–110 | **Bank**: RolandTR707 | **Scale**: minor',
  '**推荐层序**: drums → bass → pad → lead',
  '',
  '### drums',
  'gated reverb snare on 2 and 4，simple kick pattern。',
  '```',
  's("bd ~ ~ bd ~ ~ bd ~")',
  '  .bank("RolandTR707")',
  '  .gain(0.8)',
  '',
  's("~ sd ~ sd")',
  '  .bank("RolandTR707")',
  '  .gain(0.75)',
  '  .room(2)',
  '```',
  '',
  '### bass',
  'arpeggiated bass in minor，eighth notes；c2–c3，.lpf(500)。',
  '```',
  'note("c2 eb2 g2 bb2 c3 bb2 g2 eb2")',
  '  .s("sawtooth")',
  '  .lpf(500)',
  '  .gain(0.7)',
  '```',
  '',
  '### pad',
  'lush analog pad with .vowel and slow .lpf modulation；gain ~0.4，.room(2)。',
  '```',
  'note("c3 eb3 g3 bb3")',
  '  .s("juno")',
  '  .gain(0.4)',
  '  .room(2)',
  '  .attack(0.3)',
  '  .lpf(sine.range(600,2000).slow(8))',
  '```',
  '',
  '### lead',
  'saw-wave lead with delay；`.delay(0.5).delaytime(0.375)` for tempo-synced dotted-8th echo。bright melody in minor pentatonic。',
  '```',
  'note("c4 ~ eb4 ~ g4 ~ bb4 ~")',
  '  .s("sawtooth")',
  '  .gain(0.5)',
  '  .delay(0.5)',
  '  .delaytime(0.375)',
  '  .room(1.5)',
  '```',
  '',
  '**风格标志技巧**: arpeggiated lead/bass + `.delay(0.5).delaytime(0.375)` 制造 tempo-synced dotted-8th echo（0.375 = 120BPM 附点八分音符）；snare 加 `.room(2)` 模拟 gated reverb。',
].join('\n');
