export const TECHNO_GUIDE = [
  '## techno — 作曲规范',
  '**BPM**: 125–140 | **Bank**: RolandTR909 | **Scale**: minor / phrygian',
  '**推荐层序**: drums → hh → bass → lead',
  '',
  '### drums',
  'relentless four-on-the-floor kick，no swing，hard gain 0.85–0.9。`.mask("<1 1 1 0>/8")` for 8-bar tension/release cycle。',
  '```',
  's("bd*4")',
  '  .bank("RolandTR909")',
  '  .gain(0.88)',
  '  .mask("<1 1 1 0>/8")',
  '```',
  '',
  '### hh',
  'fast 16th hi-hat，.hpf(6000)，perlin gain modulation。',
  '```',
  's("hh*16")',
  '  .bank("RolandTR909")',
  '  .hpf(6000)',
  '  .gain(perlin.range(.3,.7).slow(8))',
  '```',
  '',
  '### bass',
  'monotone driving bass on the root，c1–c2，acid sweep via lpf sine。',
  '```',
  'note("c1*4")',
  '  .s("sawtooth")',
  '  .lpf(sine.range(100,400).slow(4))',
  '  .gain(0.85)',
  '```',
  '',
  '### lead',
  'acid-style 303 bleeps with .lpf sweep，sparse。',
  '```',
  'n("0(3,8)")',
  '  .scale("A4:phrygian")',
  '  .s("sawtooth")',
  '  .lpf(sine.range(200,800).slow(2))',
  '  .gain(0.5)',
  '  .decay(0.1)',
  '```',
  '',
  '**风格标志技巧**: drums `.mask("<1 1 1 0>/8")` 制造 8 小节 tension/release 循环；bass lpf sweep `sine.range(100,400).slow(4)` 制造 acid 感。',
].join('\n');
