export const TRAP_GUIDE = [
  '## trap — 作曲规范',
  '**BPM**: 130–160 | **Bank**: RolandTR808 | **Scale**: minor',
  '**推荐层序**: drums → hh → bass → pad',
  '',
  '### drums',
  'syncopated kick pattern with rests，snare on 2/4。',
  '```',
  's("bd ~ ~ bd ~ bd ~ ~")',
  '  .bank("RolandTR808")',
  '  .gain(0.85)',
  '',
  's("~ ~ sd ~ ~ ~ sd ~")',
  '  .bank("RolandTR808")',
  '  .gain(0.75)',
  '```',
  '',
  '### hh',
  'rolling 16th hi-hat，gain 0.35–0.45；occasional open hat；`.gain(saw.range(.3,.6).slow(2))` for rolling feel。',
  '```',
  's("hh*16")',
  '  .bank("RolandTR808")',
  '  .gain(saw.range(.3,.6).slow(2))',
  '',
  's("808oh(3,8)")',
  '  .bank("RolandTR808")',
  '  .gain(0.4)',
  '```',
  '',
  '### bass',
  '808 slide bass；note in c1–eb2，`.s("808bd").decay(0.6).sustain(0)`，very sparse（4–8 notes max）。',
  '```',
  'note("c1 ~ ~ eb1 ~ ~ ~ f1")',
  '  .s("808bd")',
  '  .decay(0.6)',
  '  .sustain(0)',
  '  .gain(0.9)',
  '```',
  '',
  '### pad',
  'sparse dark pad；gain ~0.25，.room(3).attack(0.5)，c3–g3 in minor。',
  '```',
  'note("c3 eb3 g3")',
  '  .s("juno")',
  '  .gain(0.25)',
  '  .room(3)',
  '  .attack(0.5)',
  '  .release(2)',
  '```',
  '',
  '**风格标志技巧**: 808 bass `.s("808bd").decay(0.6).sustain(0)` 制造 pitch glide 效果；hi-hat rolls `"hh*16"` with `.gain(saw.range(.3,.6).slow(2))` 制造律动。',
].join('\n');
