/**
 * Builds the still frames the appearance settings show as animation thumbnails.
 *
 * Each thumbnail is one frame of the animation it stands for, not a drawing of
 * it: the ASCII galaxy is captured by running its own script against a
 * recording canvas, the WebGL galaxy by re-rendering its geometry and shaders
 * on the CPU. Both are laid out at a full pane's size and then shrunk, so the
 * thumbnail reads as a screenshot of the real visual pane.
 *
 *   npm run previews:animation
 *
 * Re-run it after changing either animation. The seeds keep the output stable,
 * so a rebuild that changes nothing produces an identical file.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { captureAsciiFrame } from './animation-previews/ascii-frame';
import { renderGalaxyFrame } from './animation-previews/galaxy-frame';
import { encodePng } from './animation-previews/png';

const GALAXY_PNG = 'public/animation/previews/galaxy.png';
const ASCII_MODULE = 'src/components/settings/ascii-galaxy-frame.ts';

/* Star count is the whole ballgame at thumbnail size. The animation puts 350k
   stars on a full pane; keeping anywhere near that here lands more than one on
   every pixel, and a frame with no black left between the stars is grey fog, not
   a galaxy. 20k is around a twentieth of the pane's own density: sparse enough
   that the gaps stay black and each star reads as a star, dense enough that the
   core and the arms still hold their shape. It is a random subsample of the same
   distribution, so the galaxy is unchanged — there are just fewer stars in it.

   The size is the other half: the card is about 374 CSS px wide, so anything
   narrower than ~750px gets upscaled on a 2x display and every star smears.
   Rasterising straight at the output size keeps them a pixel wide and sharp —
   supersampling would only average them back into a haze.

   armFocus and armTightness then buy back the spiral. Thinning the field to a
   twentieth costs the pattern before it costs the stars: what carries the arms
   at 350k is density against a haze of unstructured stars, and once both are
   thin, all that is left is scatter. So the subsample keeps the stars that
   commit to an arm, and narrows the arms enough that successive windings clear
   each other instead of overlapping into a filled disk. This is the one place
   the thumbnail departs from the animation's own distribution — deliberately:
   what survives shrinking to a thumbnail is the shape, not the star count. */
const GALAXY = {
  width: 760,
  height: 470,
  outputWidth: 760,
  outputHeight: 470,
  particleCount: 20000,
  armFocus: 3,
  armTightness: 0.3,
  seed: 11,
  // The camera orbits; this is a moment where it looks down on the disk at a
  // slant, which is the angle the spiral arms read best from.
  time: 18.5,
};

/* Above the 420px height where the animation switches to its compact star
   budget, so the capture gets the full-quality galaxy. */
const ASCII = { width: 680, height: 420, seed: 7, time: 6 };

function buildGalaxy(): void {
  const rgb = renderGalaxyFrame(GALAXY);
  mkdirSync('public/animation/previews', { recursive: true });
  const png = encodePng(rgb, GALAXY.outputWidth, GALAXY.outputHeight);
  writeFileSync(GALAXY_PNG, png);
  console.log(
    `${GALAXY_PNG} — ${GALAXY.outputWidth}x${GALAXY.outputHeight}, ` +
      `${GALAXY.particleCount} stars, ${(png.length / 1024).toFixed(0)}KB`,
  );
}

function buildAscii(): void {
  const frame = captureAsciiFrame(ASCII);
  const module = `/**
 * One frame of the ASCII galaxy, captured from the animation itself.
 *
 * Generated by \`npm run previews:animation\` — do not edit by hand.
 *
 * Cells are stored row by row: a glyph per cell in \`glyphRows\` (space = unlit)
 * and its opacity in \`opacityRows\`, as a base-36 index into \`opacities\` with
 * '0' meaning unlit.
 */

export const ASCII_GALAXY_FRAME = {
  columns: ${frame.columns},
  rows: ${frame.rows},
  cellWidth: ${frame.cellWidth},
  cellHeight: ${frame.cellHeight},
  fontSize: ${frame.fontSize},
  color: '${frame.color}',
  background: '#080908',
  opacities: ${JSON.stringify(frame.opacities)},
  glyphRows: [
${frame.glyphRows.map((row) => `    ${JSON.stringify(row)},`).join('\n')}
  ],
  opacityRows: [
${frame.opacityRows.map((row) => `    ${JSON.stringify(row)},`).join('\n')}
  ],
} as const;
`;
  writeFileSync(ASCII_MODULE, module);
  console.log(`${ASCII_MODULE} — ${frame.columns}x${frame.rows} cells, ${(module.length / 1024).toFixed(0)}KB`);
}

buildGalaxy();
buildAscii();
